Security
AGuliaiev/Spring_intro pull request #11
Opened 2024-08-07 09:49 UTC by AGuliaiev

2024-08-07 11:29 UTC, Elena-Bruyako requested changes
see comments

2024-08-07 11:29 UTC, Elena-Bruyako commented on pom.xml
> +            <groupId>commons-beanutils</groupId>
remove
see comment below

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/controller/AuthenticationController.java
> +        if (!requestDto.getPassword().equals(requestDto.getRepeatPassword())) {
remove

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
```suggestion
        return new ResponseEntity<>(e.getMessage(), HttpStatus.CONFLICT);
```

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/mapper/UserMapper.java
> +
```suggestion
```

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/UserServiceImpl.java
> +        user.setEmail(requestDto.getEmail());
use mapstruct for mapping

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
use existsByEmail to avoid calling isPresent()

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/validation/FieldMatchValidator.java
> +        }
```suggestion
        Object field = new BeanWrapperImpl(value).getPropertyValue(this.firstFieldName);
        Object fieldMatch = new BeanWrapperImpl(value).getPropertyValue(this.secondFieldName);
        return Objects.equals(field, fieldMatch);
```

2024-08-07 11:29 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/UserServiceImpl.java
> +        return userMapper.toDto(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toDto(user);
```

2024-08-10 12:50 UTC, sarakhmen approved these changes

2024-08-11 10:13 UTC, merged