Add category
AGuliaiev/Spring_intro pull request #14
Opened 2024-09-04 15:48 UTC by AGuliaiev

2024-09-06 10:55 UTC, Elena-Bruyako requested changes
see comments

2024-09-06 10:55 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/dto/book/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotEmpty
```

2024-09-06 10:55 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-09-06 10:55 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
> +            name = "book_categories",
```suggestion
            name = "books_categories",
```

2024-09-06 10:55 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Category.java
> +    private Set<Book> books = new HashSet<>();
```suggestion
```

2024-09-06 10:55 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/CategoryServiceImpl.java
> +        Category category = findByIdOrThrow(id);
```suggestion
        Category category = findByIdOrThrow(id);
        mapper.updateCategoryFromDto(categoryDto, category);
```

like example

2024-09-06 10:55 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/CategoryServiceImpl.java
> +    public List<BookDtoWithoutCategoryIds> findBooksByCategoryId(Long id) {
it should be in BookController and BookService

2024-09-07 16:22 UTC, okuzan approved these changes

2024-09-08 06:17 UTC, merged