Add docker
AGuliaiev/Spring_intro pull request #17
Opened 2024-09-25 16:26 UTC by AGuliaiev

2024-09-25 18:42 UTC, ahoienko requested changes
Nice, left minor comments

2024-09-25 18:42 UTC, ahoienko commented on src/main/resources/application.properties
> -spring.datasource.password=root
Please don`t push credentials to github

2024-09-25 18:42 UTC, ahoienko commented on .env
> +DEBUG_PORT=5005
Please don`t push credentials to github, you can left them empty or add placeholders

2024-09-26 07:30 UTC, ahoienko requested changes
Nice, but there are still some work to do

2024-09-26 07:30 UTC, ahoienko commented on src/main/resources/application.properties
> -spring.datasource.password=root
This properties still should be present, they just should be empty: spring.datasource.username= or replaced with placeholders or links to system variables spring.datasource.username={DB-USERNAME}

2024-09-26 07:30 UTC, ahoienko commented on src/main/resources/application.properties
> -spring.datasource.password=root
Same with env file

2024-09-26 10:30 UTC, MentorMateAcademy approved these changes

2024-09-27 13:09 UTC, merged