add tests books and categories
AGuliaiev/Spring_intro pull request #18
Opened 2024-10-02 14:37 UTC by AGuliaiev

![Снимок экрана 2024-10-02 173309](https://github.com/user-attachments/assets/128314bb-f245-4a56-a85f-f56290f441f0)

2024-10-03 13:31 UTC, Elena-Bruyako requested changes
see comments

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +        CreateBookRequestDto requestDto = new CreateBookRequestDto();
let's create separate methods to initialize dto and entities
If you have a lot of duplication it could be TestUtils class with static methods

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +        Assertions.assertEquals(3, actual.length);
use static imports

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +    void createBook_ValidRequestDto_Success() throws Exception {
add invalid request dto test case

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +    void getBookById_ExistingBook_ReturnsBook() throws Exception {
add Invalid Id test case

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/java/org/example/springintro/controller/CategoryControllerTest.java
> +class CategoryControllerTest {
same comments as in BookControllerTest

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/java/org/example/springintro/repository/book/BookRepositoryTest.java
> +        Book book1 = books.get(0);
using numbers for naming is bad practice

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/resources/database/books/add-books-and-categories.sql
> +INSERT INTO books_categories (book_id, category_id) VALUES
you can replace VALUES to new line to increase readability

2024-10-03 13:31 UTC, Elena-Bruyako commented on src/test/resources/database/books/add-books-and-categories.sql
> +INSERT INTO books (id, title, author, isbn, price, description, cover_image, is_deleted) VALUES
you can replace VALUES to new line to increase readability

2024-10-04 08:45 UTC, sarakhmen requested changes
please make suggested changes before requesting the code review

2024-10-07 07:21 UTC, liliia-ponomarenko requested changes
Good job! Let's improve your solution ;)

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/CategoryControllerTest.java
> +@Transactional
Why do you use Transactional here?

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +        teardown(dataSource);
Why do you call teardown in beforeAll method?

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +@Transactional
Why do you need Transactional here?

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +    private BookController bookController;
Why do you need it for integration testing?

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +        MockitoAnnotations.openMocks(this);
Why do you need it?

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +        when(bookService.findBooksByCategoryId(EXISTING_ID)).thenReturn(books);
Don't use mocks for integration testing

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +                .thenReturn(Collections.emptyList());
the same

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/services/BookServiceTest.java
> +        CreateBookRequestDto requestDto = new CreateBookRequestDto();
you can use your TestUtil class to create objects

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/resources/database/books/remove-books-and-categories.sql
> +
```suggestion
```

2024-10-07 07:21 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/services/CategoryServiceTest.java
> +class CategoryServiceTest {
the same about using TestUtils. Also, you can use Spy for mappers and simplify your test cases ;)

2024-10-08 06:30 UTC, liliia-ponomarenko approved these changes
Good job! But please see my comments ;)

2024-10-08 06:30 UTC, liliia-ponomarenko commented on src/main/java/org/example/springintro/exception/CustomGlobalExceptionHandler.java
> +    }
it doesn't apply to tests, but it's too general exception to catch. Don't do that ;)

2024-10-08 06:30 UTC, liliia-ponomarenko commented on src/test/java/org/example/springintro/controller/BookControllerTest.java
> +        teardown(dataSource);
call `teardown` AfterEach

2024-10-08 09:44 UTC, merged