Spring data jpa
AGuliaiev/Spring_intro pull request #2
Opened 2024-04-27 04:47 UTC by AGuliaiev

2024-04-27 05:32 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/SpringIntroApplication.java
> +
```suggestion
```

2024-04-27 05:32 UTC, Elena-Bruyako commented on pom.xml
> +    <artifactId>spring-intro</artifactId>
didn't find required dependency
Look at HW description: Налаштувати залежності. Переконайся, що pom.xml містить залежність Liquibase Core і Liquibase Maven Plugin:

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=validate
add `server.servlet.context-path=/api`

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
> +@Where(clause = "is_delete=false")
`@Where` is deprecated, use `@SQLRestriction`

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
>  @Data
Don't use `@Data` for entities

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
>      private String isbn;
Add constraints: nullable = false, unique - true
Check other fields according to the task description

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
> +    @Column(nullable = false)
```suggestion
```

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/repository/BookRepository.java
> +    Book save(Book book);
All these methods provide JpaRepository

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/BookServiceImpl.java
> +    @Autowired
Redundant

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/services/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.getTitle());
You can use Mapper method 
`bookMapper.updateBookFromDto(requestDto, book);`

where 
`void updateBookFromDto(CreateBookRequestDto book, @MappingTarget Book entity);`

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +              - column:
Add required constraints for columns according to the task description

2024-04-27 05:32 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-delete-column-to-book-table.yaml
> +              - column:
This column should be in 01-create-books-table.yaml

2024-05-01 05:21 UTC, Elena-Bruyako requested changes

2024-05-01 05:21 UTC, Elena-Bruyako commented on pom.xml
> +            <version>${liquibase.version}</version>
spring boot parent already provides liquibase version

2024-05-01 05:21 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
>      private String isbn;
Not fixed

2024-05-01 05:21 UTC, Elena-Bruyako commented on src/main/java/org/example/springintro/model/Book.java
>      private String isbn;
<img width="278" alt="Screenshot 2024-05-01 at 08 19 12" src="https://github.com/AGuliaiev/Spring_intro/assets/14053156/2abd5215-665b-4d02-9872-f0542f9a56b6">

2024-05-01 05:21 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +              - column:
Not fixed

2024-05-01 19:19 UTC, okuzan approved these changes

2024-05-01 19:19 UTC, okuzan commented on src/main/java/org/example/springintro/model/Book.java
> +@SQLRestriction(value = "is_delete=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_delete = TRUE WHERE id=?")
@SQLRestriction(value = "is_delete = FALSE")
```

2024-05-01 19:19 UTC, okuzan commented on src/main/java/org/example/springintro/services/impl/BookServiceImpl.java
> +    }
you can use mapstruct to map list to list automatically, without streams

2024-07-16 14:23 UTC, merged