Master query
AGuliaiev/Spring_intro pull request #5
Opened 2024-06-07 13:54 UTC by AGuliaiev

2024-06-07 14:38 UTC, okuzan requested changes

2024-06-07 14:38 UTC, okuzan commented on src/main/java/org/example/springintro/repository/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException("Can't find correct"
NoSuchElementException

2024-06-07 14:38 UTC, okuzan commented on src/main/java/org/example/springintro/repository/book/spec/AuthorSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("author")
to constant, same with title

2024-06-07 14:38 UTC, okuzan commented on src/main/java/org/example/springintro/repository/book/BookSpecificationBuilder.java
> +
don't leave emtpy lines after method/class definitions

2024-06-17 19:26 UTC, sarakhmen approved these changes

2024-07-16 12:34 UTC, merged