Glob except
AGuliaiev/Spring_intro pull request #6
Opened 2024-07-12 11:06 UTC by AGuliaiev

2024-07-12 13:53 UTC, okuzan commented on src/main/java/org/example/springintro/services/impl/BookServiceImpl.java
> +                );
extract repeated logic to a private method

2024-07-12 13:54 UTC, okuzan requested changes

2024-07-12 13:54 UTC, okuzan commented on src/main/java/org/example/springintro/services/BookService.java
> +
```suggestion
```

2024-07-12 13:54 UTC, okuzan commented on src/main/java/org/example/springintro/model/Book.java
> +@SQLRestriction(value = "is_delete=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_delete = TRUE WHERE id = ?")
@SQLRestriction(value = "is_delete = FALSE")
```

2024-07-12 13:54 UTC, okuzan commented on pom.xml
> +</project>
```suggestion
</project>

```

2024-07-13 08:25 UTC, Elena-Bruyako requested changes
Changes in PR are related not only to Global Exc HW, but to previous HWs also. 
You have 5 open PRs. If they were approved by mentors, merge to main and rebase this branch

2024-07-16 14:23 UTC, merged